name: GitHub Pages

on:
  push:
    paths:
      - docs/**
      - docs-ve/**
  workflow_dispatch:

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages.yml@main
    with:
      publish_dir: docs/storybook-static
      cname: shiraha.js.org
